### ISSUE TITLE
gitlab.com/onf-internship/ueransim inaccessible

### ISSUE THREAD

**Issue by yoursunny** [opennetworkinglab/aether-ueransim#3]
[README.md](https://github.com/opennetworkinglab/aether-ueransim/blob/042a882cbb2ca222875832ea59997179d669275a/README.md) says:

> To download the ueransim repository, use the following command:
> `git clone https://gitlab.com/onf-internship/ueransim.git`

However, this repository seems to be private.
Please make it public, thanks.

**Comment by kunal14kapoor** [comment]
@yoursunny Thanks for highlighting this. The URL needs to be updated, till then `https://github.com/opennetworkinglab/aether-ueransim.git` can be used for aether-ueransim.
